import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawn } from "node:child_process";

const currentDir = path.dirname(fileURLToPath(import.meta.url));
const backendDir = path.resolve(currentDir, "..");
const outputDir = path.resolve(backendDir, "artifacts", "lambda");

function run(command, args, options = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, { stdio: "inherit", shell: true, ...options });
    child.on("close", (code) => {
      if (code === 0) {
        resolve();
        return;
      }

      reject(new Error(`${command} ${args.join(" ")} failed with exit code ${code}`));
    });
  });
}

async function main() {
  await rm(outputDir, { recursive: true, force: true });
  await mkdir(outputDir, { recursive: true });

  await cp(path.resolve(backendDir, "dist"), path.resolve(outputDir, "dist"), { recursive: true });
  await cp(path.resolve(backendDir, "package.json"), path.resolve(outputDir, "package.json"));
  await cp(path.resolve(backendDir, "package-lock.json"), path.resolve(outputDir, "package-lock.json"));

  await run("npm", ["ci", "--omit=dev"], { cwd: outputDir });

  const readme = [
    "# Lambda Artifact",
    "",
    "This directory is generated by `npm run package:lambda`.",
    "It contains production dependencies plus compiled backend output for Lambda.",
    ""
  ].join("\n");

  await writeFile(path.resolve(outputDir, "README.md"), readme, "utf8");
  console.log(`Lambda artifact prepared at ${outputDir}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
